version: '2.3'
services:
  wsadje-test:
    container_name: wsadje-test
    image: iki-onto-test
    environment:
      WAIT_FOR_ROSCORE: 1
      #ROS_IP: $ROS_IP
      #ROS_MASTER_URI: $ROS_MASTER_URI
      #WAIT_FOR_ROSCORE: 0
      ROS_IP: 127.0.0.1
      ROS_MASTER_URI: http://localhost:11311
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    restart: 'unless-stopped'
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
    command: tail -f /dev/null